# Generated by Django 5.0.3 on 2024-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quorum_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='primary_sponsor',
        ),
        migrations.AddField(
            model_name='bill',
            name='sponsor_id',
            field=models.IntegerField(db_column='sponsor_id', default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bill',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
